### ISSUE TITLE
Issues in GEMS/JAVA/3. Object Oriented Programming/IAssess/2.java

### ISSUE THREAD

**Issue by tusharpangare** [xurdee/GEMS#1]
1. In PremiumStall.java **setProjector** method needs to be updated. Instead of giving tvSet as a **parameter**, you can change it to the **projector**.  So that set method will work.
2. Same goes with ExecutiveStall.java where there is an issue with **setScreen** same as above.

You can refer to the updated code here:
[https://github.com/tusharpangare/Ebox-Java-/blob/main/assess2.java](https://github.com/tusharpangare/Ebox-Java-/blob/main/assess2.java)

**Comment by xurdee** [comment]
Thanks Tushar for bringing it to my notice. I have fixed the code accordingly.
